from __future__ import annotations

import csv
import json
import os
from pathlib import Path

import numpy as np
import torch
from batchgenerators.dataloading.nondet_multi_threaded_augmenter import NonDetMultiThreadedAugmenter
from batchgenerators.dataloading.single_threaded_augmenter import SingleThreadedAugmenter

from nnunetv2.training.dataloading.data_loader import nnUNetDataLoader
from nnunetv2.training.dataloading.nnunet_dataset import infer_dataset_class
from nnunetv2.training.nnUNetTrainer.variants.nnUNetTrainerPseudoWeighted_500ep_LR5e4 import (
    nnUNetTrainerPseudoWeighted_500ep_LR5e4,
)
from nnunetv2.utilities.default_n_proc_DA import get_allowed_n_proc_DA


class nnUNetTrainer_D007ETAwareRegionLoss500(nnUNetTrainerPseudoWeighted_500ep_LR5e4):
    """Final mixed-supervision trainer base with external ET-aware weights.

    This trainer intentionally keeps the D007 standard FT500 optimizer, LR,
    PolyLR scheduler, and pseudo-label curriculum. It adds:
    - oversample_foreground_percent = 0.5
    - required fold-specific sampling weights supplied as private JSON input
    - normalized replacement sampling over one pooled training dataset

    The checkpoint-compatible subclass adds the paper's trainable ET/TC/WT
    auxiliary head.
    """

    case_weight_root_env = "D007_ETAWARE_CASE_WEIGHT_ROOT"

    def __init__(
        self,
        plans: dict,
        configuration: str,
        fold: int,
        dataset_json: dict,
        device: torch.device = torch.device("cuda"),
    ):
        super().__init__(plans, configuration, fold, dataset_json, device)
        self.num_epochs = 500
        self.initial_lr = 5e-4
        self.oversample_foreground_percent = 0.5
        self.case_weights = self._load_case_weights()
        self._ensure_logger_keys()
        self.print_to_log_file("D007 external ET-aware sampling base initialized")
        self.print_to_log_file(f"  oversample_foreground_percent: {self.oversample_foreground_percent}")
        self.print_to_log_file(f"  case_weights_loaded: {len(self.case_weights)}")

    def _manifest_path(self) -> Path:
        raw_root = Path(os.environ.get("nnUNet_raw", "nnUNet_data/nnUNet_raw"))
        dataset_root = raw_root / self.plans_manager.dataset_name
        return dataset_root / "dataset007_case_manifest.csv"

    def _load_case_roles(self) -> dict[str, str]:
        path = self._manifest_path()
        roles: dict[str, str] = {}
        role_map = {
            "original_labeled": "original_labeled",
            "pseudo_labeled_qc_strict": "pseudo_labeled_highconf",
            "pseudo_labeled_ml_strict": "pseudo_labeled_highconf",
            "excluded": "dycon_unlabeled",
            "ml_unlabeled_remainder": "dycon_unlabeled",
        }
        if not path.is_file():
            raise RuntimeError(f"Missing final Dataset007 case manifest: {path}")
        with path.open(newline="") as f:
            reader = csv.DictReader(f)
            if "case_id" not in (reader.fieldnames or []) or "role" not in (reader.fieldnames or []):
                raise RuntimeError(f"{path} must contain case_id and role columns")
            for row in reader:
                raw_role = row.get("role", "")
                roles[row["case_id"]] = role_map.get(raw_role, raw_role)
        if not roles:
            raise RuntimeError(f"Final Dataset007 manifest is empty: {path}")
        return roles

    def _case_weight_root(self) -> Path:
        return Path(os.environ.get(self.case_weight_root_env, "private_assets/case_weights"))

    def _load_case_weights(self) -> dict[str, float]:
        path = self._case_weight_root() / f"case_weights_fold{int(self.fold)}.json"
        if not path.is_file():
            raise RuntimeError(
                f"Missing fold-specific ET-aware weights: {path}. "
                "Weights are required private inputs and are not generated by the public code."
            )
        with path.open() as f:
            data = json.load(f)
        if not isinstance(data, dict):
            raise RuntimeError(f"Weight JSON must contain an object: {path}")
        weights = data.get("case_weights", data)
        if not isinstance(weights, dict) or not weights:
            raise RuntimeError(f"case_weights must be a nonempty JSON object: {path}")
        parsed: dict[str, float] = {}
        for case_id, value in weights.items():
            if not isinstance(case_id, str) or not case_id:
                raise RuntimeError(f"Every weight key must be a nonempty case ID: {path}")
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise RuntimeError(f"Weight for {case_id} must be a JSON number: {value!r}")
            parsed[case_id] = float(value)
        values = np.asarray(list(parsed.values()), dtype=np.float64)
        if values.size == 0 or not np.isfinite(values).all():
            raise RuntimeError(f"Invalid or empty case weights: {path}")
        if float(values.min()) < 1.1 or float(values.max()) > 2.0:
            raise RuntimeError(
                f"Final-run case weights must be in [1.1, 2.0], got "
                f"[{values.min()}, {values.max()}] in {path}"
            )
        return parsed

    def _sampling_probabilities_for_dataset(self, dataset) -> np.ndarray:
        identifiers = [str(case_id) for case_id in dataset.identifiers]
        expected = set(identifiers)
        actual = set(self.case_weights)
        if actual != expected:
            missing = sorted(expected - actual)
            extra = sorted(actual - expected)
            raise RuntimeError(
                f"Fold {self.fold} weight IDs do not match training IDs: "
                f"missing={missing[:5]}, extra={extra[:5]}"
            )
        weights = np.asarray([self.case_weights[case_id] for case_id in identifiers], dtype=np.float64)
        weights = weights / weights.sum()
        self.print_to_log_file(
            f"D007 ET-aware replacement sampling active for fold {self.fold}: "
            f"n_train={len(identifiers)}, normalized_sum={weights.sum():.12f}, "
            f"min_p={weights.min():.6e}, max_p={weights.max():.6e}"
        )
        return weights

    def get_dataloaders(self):
        if self.dataset_class is None:
            self.dataset_class = infer_dataset_class(self.preprocessed_dataset_folder)

        patch_size = self.configuration_manager.patch_size
        deep_supervision_scales = self._get_deep_supervision_scales()
        (
            rotation_for_DA,
            do_dummy_2d_data_aug,
            initial_patch_size,
            mirror_axes,
        ) = self.configure_rotation_dummyDA_mirroring_and_inital_patch_size()

        tr_transforms = self.get_training_transforms(
            patch_size,
            rotation_for_DA,
            deep_supervision_scales,
            mirror_axes,
            do_dummy_2d_data_aug,
            use_mask_for_norm=self.configuration_manager.use_mask_for_norm,
            is_cascaded=self.is_cascaded,
            foreground_labels=self.label_manager.foreground_labels,
            regions=self.label_manager.foreground_regions if self.label_manager.has_regions else None,
            ignore_label=self.label_manager.ignore_label,
        )
        val_transforms = self.get_validation_transforms(
            deep_supervision_scales,
            is_cascaded=self.is_cascaded,
            foreground_labels=self.label_manager.foreground_labels,
            regions=self.label_manager.foreground_regions if self.label_manager.has_regions else None,
            ignore_label=self.label_manager.ignore_label,
        )

        dataset_tr, dataset_val = self.get_tr_and_val_datasets()
        dl_tr = nnUNetDataLoader(
            dataset_tr,
            self.batch_size,
            initial_patch_size,
            self.configuration_manager.patch_size,
            self.label_manager,
            oversample_foreground_percent=self.oversample_foreground_percent,
            sampling_probabilities=self._sampling_probabilities_for_dataset(dataset_tr),
            pad_sides=None,
            transforms=tr_transforms,
            probabilistic_oversampling=self.probabilistic_oversampling,
        )
        dl_val = nnUNetDataLoader(
            dataset_val,
            self.batch_size,
            self.configuration_manager.patch_size,
            self.configuration_manager.patch_size,
            self.label_manager,
            oversample_foreground_percent=self.oversample_foreground_percent,
            sampling_probabilities=None,
            pad_sides=None,
            transforms=val_transforms,
            probabilistic_oversampling=self.probabilistic_oversampling,
        )

        allowed_num_processes = get_allowed_n_proc_DA()
        if allowed_num_processes == 0:
            mt_gen_train = SingleThreadedAugmenter(dl_tr, None)
            mt_gen_val = SingleThreadedAugmenter(dl_val, None)
        else:
            mt_gen_train = NonDetMultiThreadedAugmenter(
                data_loader=dl_tr,
                transform=None,
                num_processes=allowed_num_processes,
                num_cached=max(6, allowed_num_processes // 2),
                seeds=None,
                pin_memory=self.device.type == "cuda",
                wait_time=0.002,
            )
            mt_gen_val = NonDetMultiThreadedAugmenter(
                data_loader=dl_val,
                transform=None,
                num_processes=max(1, allowed_num_processes // 2),
                num_cached=max(3, allowed_num_processes // 4),
                seeds=None,
                pin_memory=self.device.type == "cuda",
                wait_time=0.002,
            )
        _ = next(mt_gen_train)
        _ = next(mt_gen_val)
        return mt_gen_train, mt_gen_val
